export const QUERY_KEY = {
  user: "user",
  userCustomer: "userCustomer",
  userDeliverer: "userDeliverer",
  delivererInfo: "delivererInfo",
  customerInfo: "customerInfo",
  login: "login",
  logout: "logout",
  registerCustomer: "registerCustomer",
  registerDeliverer: "registerDeliverer",
  customerDeliveryRequestList: "customerDeliveryRequestList",
  availableDeliveryRequestList: "availableDeliveryRequestList",
  delivererDeliveryRequestList: "delivererDeliveryRequestList",
  createDeliveryRequest: "createDeliveryRequest",
  applyForDeliveryRequest: "applyForDeliveryRequest",
  approveDeliveryRequest: "approveDeliveryRequest",
  pickupDeliveryRequest: "pickupDeliveryRequest",
  deliverDeliveryRequest: "deliverDeliveryRequest",
};
